server:
  port: 8080
  base_url: ""
log:
  level: info
  filename: data/logs/app.log
  db_filename: data/logs/db.log
  max_size: 100
  max_backups: 3
  max_age: 7
  compress: true
  log_console: true
  show_db_log: false
  db_log_level: info
api:
  mode: redirect
  enable_mkt_fallback: false
  enable_on_demand_fetch: false
cron:
  enabled: true
  daily_spec: 20 8-23/4 * * *
retention:
  days: 0
db:
  type: sqlite
  dsn: data/bing_paper.db
storage:
  type: local
  local:
    root: data/picture
  s3:
    endpoint: ""
    region: ""
    bucket: ""
    access_key: ""
    secret_key: ""
    public_url_prefix: ""
    force_path_style: false
  webdav:
    url: ""
    username: ""
    password: ""
    public_url_prefix: ""
admin:
  password_bcrypt: $2a$10$fYHPeWHmwObephJvtlyH1O8DIgaLk5TINbi9BOezo2M8cSjmJchka
token:
  default_ttl: 168h
feature:
  write_daily_files: true
web:
  path: web
fetcher:
  regions:
    - zh-CN
    - en-US
    - ja-JP
    - en-AU
    - en-GB
    - de-DE
    - en-NZ
    - en-CA
    - fr-FR
    - it-IT
    - es-ES
    - pt-BR
    - ko-KR
    - en-IN
    - ru-RU
