server:
  port: 8080
  base_url: ""

log:
  level: info
  filename: data/logs/app.log
  db_filename: data/logs/db.log
  max_size: 100
  max_backups: 3
  max_age: 7
  compress: true
  log_console: true
  show_db_log: false
  db_log_level: info

api:
  mode: local # local | redirect

cron:
  enabled: true
  daily_spec: "0 10 * * *"

retention:
  days: 0

db:
  type: sqlite # sqlite | mysql | postgres
  dsn: data/bing_paper.db

storage:
  type: local # local | s3 | webdav
  local:
    root: data/picture
  s3:
    endpoint: ""
    region: ""
    bucket: ""
    access_key: ""
    secret_key: ""
    public_url_prefix: ""
    force_path_style: false
  webdav:
    url: ""
    username: ""
    password: ""
    public_url_prefix: ""

admin:
  password_bcrypt: "$2a$10$fYHPeWHmwObephJvtlyH1O8DIgaLk5TINbi9BOezo2M8cSjmJchka" # 默认密码: admin123

token:
  default_ttl: 168h

feature:
  write_daily_files: true

web:
  path: web
